### PR TITLE
fix(classNames context): general improvements 

### PR DESCRIPTION
**Pull request by danilowoz**
- Make an identifier mandatory;
- Drop code-hike dependency;
- Drop THEME_PREFIX need to every className;

Closes https://github.com/codesandbox/sandpack/issues/714

### CODE REVIEW

**Comment by Jokcy** [comment]
Greate! Just have time to work with this issue and see your PR, the API looks similar as I imagine, can't wait for the new release.

**Comment by Jokcy** [comment]
Hi @danilowoz , I used to try to keep the traditional `classNames` usage and just implement `useClassNames` hook for classes need prefix and class name map, like this:
```js
import { classNames } from "../utils/classNames";

const classNamesWithPrefix = useClassNames()

<div className={classNames(classNamesWithPrefix('sandpack-class-1', ...classNeedPrefix), buttonClassName, ...classesWithoutPrefix)}></div>
```

The only difference is it try to fit the api of `classnames` or `clsx` package.

But since we implement `classNames` ourself instead of import another package, I suppose it's not a big deal.

**Comment by Jokcy** [comment]
@danilowoz Any plan to merge this PR?

**Comment by danilowoz** [comment]
As I will be off for a couple of weeks, I don't want to introduce any disruptive change. Let's get this done as soon as I am back.

**Pull request merged**
