### PR TITLE
fix: husky is fail to work

### PR DESCRIPTION
**Pull request by uyarn**
Just realise that the husky is fail to work, since the setting of husky is different between v4 and v5. 
In v5, the configuration of husky is moved into the `.husky` folder like this Pull Request.

### CODE REVIEW

**Comment by uyarn** [comment]
run `npx husky init` to init this folder.

**Comment by alexnm** [comment]
great, thanks!

**Comment by uyarn** [comment]
would like to contribute more in this project :)

**Comment by alexnm** [comment]
nice to hear that, feel free to open discussions or directly new PRs if you have improvements to the project. we're a bit laggy with the roadmap for this project, but will try to make things easier asap

**Pull request merged**
