### PR TITLE
add icons to distinguish file and directory within the FileExplorer

### PR DESCRIPTION
**Pull request by uyarn**
Hi, @alexnm
     I make a simple change in FileExplorer :), by which I add FileIcon and DirectoryIcon to distinguish file and directory. The color of these icons would change following the theme as well. What's more, I add another story of Explorer in the storybook of Explorer Component as well,  hope it can help you have a quick preview of this pull request. Thanks ~

### CODE REVIEW

**Comment by alexnm** [comment]
Hey @uyarn just to let you know I saw this PR, but I need more time to review it and I'm out these days until Tuesday

**Comment by uyarn** [comment]
> Hey @uyarn just to let you know I saw this PR, but I need more time to review it and I'm out these days until Tuesday

never mind, I would make some change in this PR as well:). Enjoy your trip!

**Comment by alexnm** [comment]
merging this for now so you can use the FileExplorer from the new version I'm publishing. We might design the component in the future to be more inline with the rest of sandpack, but for now it's not a priority.

**Comment by uyarn** [comment]
Thank you so much @alexnm ~

**Comment by alexnm** [comment]
thank you for the contribution. btw, just noticed after publishing 0.1.0 that the file explorer is actually not exported from the index file. didn't pay attention to this. will fix it in a next release

**Comment by uyarn** [comment]
> thank you for the contribution. btw, just noticed after publishing 0.1.0 that the file explorer is actually not exported from the index file. didn't pay attention to this. will fix it in a next release

Got it. Hope can contribute more in the future and feel free to assign some tasks in the project to me if I can help, cheers~

**Pull request merged**
