### PR TITLE
feat(SandpackTests): Add SandpackTests component

### LINKED ISSUE #112: Feature request: Add tests panel support
# Tell us how you think we can improve Sandpack

## Packages affected

- [x] sandpack-client
- [x] sandpack-react

## What is this feature?

Would it be possible to support test files? Currently on codesandbox.io I can configure the sandbox view to show the `tests` panel which can run the tests.

## How would your idea work?

Much like the `sandpack-react` does currently but with an additional `view` option which supports `tests` that instead of rendering the React component into the DOM it would run the test file with jest and display the results.

## Do you have any examples of how you would like to see us implement it?

Sorry no real examples but the use case I have in mind is for a [jest-extended docs site](https://github.com/jest-community/jest-extended) with an embedded repl (powered by Sandpack) that can run the examples for each matcher.

This would be preferable to creating a codesandbox per matcher and manually embedding it.

Here's an example of what I've currently configured in a [sandbox](https://codesandbox.io/s/jest-extended-sandbox-forked-dbeyz?file=/matchers/toBeNil.test.js) if it's of any help.

I'm more than happy to get involved with building this if it's of value to the project, would just need some pointers on where to begin 😆

### PR DESCRIPTION
**Pull request by mattphillips**
CodeSandbox logoCodeSandbox logo&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/mattphillips/sandpack/mp/sandpack-test?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=mattphillips&repo=sandpack&branch=mp/sandpack-test">VS Code</a>

## What kind of change does this pull request introduce?

 - This PR adds a new `SandpackTests` component.
 - I've added the missing test related types to the sandpack-client project's `SandpcakMessage` type. Type defs have been adapted from: [codeandbox tests component](https://github.com/codesandbox/codesandbox-client/blob/389073613e06eee944231f4aeef9dfa746c1b947/packages/app/src/app/components/Preview/DevTools/Tests/index.tsx#L68)
 - I've also bumped `package-build-stats` dependency to a newer version. I was unable to build the project because of a node-sass issue related to the older version of this package ([see related](https://github.com/pastelsky/package-build-stats/issues/40))

## What is the current behavior?

This feature does not exist in Sandpack but builds on top of codesandbox's tests panel. 

It is also the result of this [Tweet](https://twitter.com/mattphillipsio/status/1561797703222321153)

Closes #112 

## What is the new behavior?

The component handles:

 - Running multiple files tests
 - Running individual test files
 - Displaying test results
   - Including in a verbose mode
 - Handles file errors
 - Handles no tests file
 - Formats error messages
 - Should work with all themes

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Manually tested
2. Added a story in storybook for each of the above features

## Checklist

- [x] Documentation;
- [x] Storybook (if applicable);
- [ ] Tests;
- [ ] Ready to be merged;

## Todo before merging
 - Update the docs
 - Go over css to make sure it follows project style 

## Future Todos

I'll get to these once this PR is ready to merge.

 - Add some nicer styling to the `verbose` toggle. (Am still new to `stitches` and it doesn't feel that intuitive 😅).
 - `jest-lite` in codesandbox doesn't support `jsx` files but should so a PR is needed to change this [line](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/sandbox/eval/tests/jest-lite.ts#L214)
 - `jest-lite` in codesandbox doesn't correctly handle focussed tests (`.only`). It treats focussed test as the only test for all files when it should be scoped to a `describe` level.
 - Expose an `onComplete` callback to `SandpackTests` for consumers to listen for results
 - Expose additional props that confirm to this projects API style for components e.g. `style`/`className` to customise the root `SandpackStack`.

---

Overall this is pretty much done but I still have a few bits to do. I think now would be a good time to get some eyes on this for some feedback.

cc/ @CompuIves @danilowoz PR as promised 😃

### CODE REVIEW

**Comment by nicobytes** [comment]
Wow, great! I hope this component be accepted soon!

I'm working in a component for tests, but this proposal is so completed

image

**Comment by mattphillips** [comment]
Hey @danilowoz, I've just been thinking about writing some docs for this PR and it got me wondering if we would want a `tests` template too?

I've had a quick look into how the templates work and it seems they only show the `activeFile` as being visible by default and only render the `Preview` component by default. To make a `tests` template we'd need to change some of this behaviour to allow templates to specify which component to render (`SandpackPreview` / `SandpackTests`).

An extension on this is that we could also add an example test to each template and an option whether to display the `Tests` panel as part of the Sandpack options when using templates (this would probably default to false).

Curious to hear your thoughts? 😄

**Comment by danilowoz** [comment]
@mattphillips loved the idea! Let's do it!

So, here's a quick summary of what's missing:

- [ ] Add a new template: render the test component instead of preview;
- [ ] Add watch mode: introduce a new toggle on the top bar;
- [ ] Documentation and examples;
- [ ] Make sure all colors: check with designers what's the to do here;

**Comment by mattphillips** [comment]
Yeah that summary looks good to me 👍

One other thing we could do (could be in another PR) is to add a test example to each of the other templates

**Comment by danilowoz** [comment]
**Changelog**
- Add new SandpackTest component: watch and verbose options;
- Introduce a new hook: `useSandpackClient`, which is responsible for registering a new client and returning its instance;
- New template file: `tests-ts`;
- Sandpack component introduces a new layout view: test mode;

**Review by danilowoz — APPROVED** [review]
🚀 🚀 🚀 🚀 🚀 🚀

**Pull request merged**
