### PR TITLE
fix(file-explorer): adds property not to show hidden files

### LINKED ISSUE #482: SandpackFileExplorer show hidden files
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

`<SandpackFileExplorer>` show hidden files

## What were you doing when the problem occurred?

I expected that SandpackFileExplorer shows only `/index.js` and `/index2.js`.
It means that only show same files with Tab files.

But actually, SandpackFileExplorer shows `/src/index.js`, `/hidden.js` and vinilla template files.

image

```tsx
import {
  SandpackProvider,
  SandpackLayout,
  SandpackFileExplorer,
  SandpackCodeEditor
} from "@codesandbox/sandpack-react";

export default function App() {
  return (
    <SandpackProvider
      files={{
        "/index.js": {
          code: "// index.js",
          active: true
        },
        "/index2.js": {
          code: "// index2.js"
        },
        "/src/index.js": {
          code:
            "// this file is generated by vanilla template, but it is not needed",
          hidden: true
        },
        "/hidden.js": {
          code: "// hidden.js",
          hidden: true
        }
      }}
      customSetup={{
        entry: "/index.js"
      }}
      template={"vanilla"}
    >
      <SandpackLayout>
        <SandpackFileExplorer />
        <SandpackCodeEditor />
      </SandpackLayout>
    </SandpackProvider>
  );
}
```

### What steps can we take to reproduce the problem?

I just use SandpackFileExplorer + `hidden` property.
I think that `options.visibleFiles` is same behavior

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/sandpack-parcel-sandpackfileexplorer-hidden-ejzfhy?file=/src/App.js

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |     1.0.4         |
| Browser                 |      Firefox/Chrome        |
| Operating System        |              |

### PR DESCRIPTION
**Pull request by jerrywu001**
## What kind of change does this pull request introduce?

provide a property(enableAutoHiddenFile: default value is false) in FIleExplorer Component that indicates whether files in the file tree are automatically hidden.

## What is the current behavior?

Closes #482 

## What is the new behavior?

My solution is to provide a property that indicates whether files in the file tree are automatically hidden.LIke this:

```jsx
// enableAutoHiddenFile: boolean; // default: false
<SandpackProvider
    files={{
      "/index.js": {
        code: "// index.js",
        active: true
      },
      "/index2.js": {
        code: "// index2.js"
      },
      "/src/index.js": {
        code:
          "// this file is generated by vanilla template, but it is not needed",
        hidden: true
      },
      "/hidden.js": {
        code: "// hidden.js",
        hidden: true
      }
    }}
    customSetup={{
      entry: "/index.js"
    }}
    template={"vanilla"}
  >
    <SandpackLayout>
      <SandpackFileExplorer enableAutoHiddenFile />
      <SandpackCodeEditor />
    </SandpackLayout>
  </SandpackProvider>
```

image

image

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

add story: http://localhost:6006/?path=/story/bug-reports-issues--issue-482

## Checklist

- [ ] Documentation;
- [x] Storybook (if applicable);
- [ ] Tests;
- [x] Ready to be merged;

### CODE REVIEW

**Comment by danilowoz** [comment]
Thanks, @jerrywu001 for fixing this issue! I took this change to refactor the class component to functional components and add some tests. Let me know what you think about these changes.

**Comment by danilowoz** [comment]
@jerrywu001 what if we rename it from `enableAutoHiddenFile` to `autoHiddenFiles`? As the prop is a boolean, doesn't the `enable` seems redundant?

**Comment by jerrywu001** [comment]
> @jerrywu001 what if we rename it from `enableAutoHiddenFile` to `autoHiddenFiles`? As the prop is a boolean, doesn't the `enable` seems redundant?

Thanks, understand. What should I do next?

**Comment by danilowoz** [comment]
> Thanks, understand. What should I do next?
Your changes look good to me, but let me know if you want to review the PR and my changes. It's always good having another pair of eyes

Then it's ready to go!

**Comment by jerrywu001** [comment]
> > Thanks, understand. What should I do next?
> > Your changes look good to me, but let me know if you want to review the PR and my changes. It's always good having another pair of eyes
> 
> Then it's ready to go!

Your changes are perfect, there is no need to review the PR.

**Comment by danilowoz** [comment]
I believe it's because your user doesn't have write access to this repo, and then these actions can't perform some operations. But it's fine, don't worry

**Pull request merged**
