### PR TITLE
docs: add guide for real time collab using firepad

### LINKED ISSUE #405: [Feature Request] Multi-user support
# Tell us how you think we can improve Sandpack

## Packages affected

-   [X] sandpack-client

## What is this feature?

Offer documentation or first-class support for setting up multiple user editing in Sandbox.

### PR DESCRIPTION
**Pull request by hussamkhatib**
## What kind of change does this pull request introduce?

It fixes #405 

## What is the current behavior?

N/A

## What is the new behavior?

N/A

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

N/A

## Checklist

- [x] Documentation;
- [ ] Storybook (if applicable);
- [ ] Tests;
- [ ] Ready to be merged;

### CODE REVIEW

**Comment by hussamkhatib** [comment]
Hi @danilowoz
Consider this as an initial draft.
I was not able to run the example in codesandbox, so I created a repo demonstrating the use case.
I didn't add the live demo as well as I am getting this CORS(attached image below). However this works fine if env variables are hard-coded. In case you want the example to be in csb,I have checked on the "allow edits by maintainers" , so you can add your own link
image

**Comment by danilowoz** [comment]
Hey @hussamkhatib, sorry for taking too long to respond. First, thanks for creating this example. It's really exciting.

The implementation looks good to me, but I couldn't test the live collaboration. It seems that it's missing some part that updates the code:
Screenshot 2022-07-21 at 16 26 45

Here's the project running: https://codesandbox.io/p/github/danilowoz/Real-time-collaborative-sandpack/draft/cocky-hofstadter

**Comment by hussamkhatib** [comment]
Hi @danilowoz,
Thank you for trying it out  😄.
It should work now. [link to repo](https://github.com/hussamkhatib/Real-time-collaborative-sandpack)
The issue was with the env variables. I have hardcoded the values directly and is working now.
I didn't realize I hadn't put  `.env` in `.gitignore` file in the first place.
Let me know after you try and everything looks good, I'll go ahead and delete the firebase service for this project

**Comment by danilowoz** [comment]
Awesome, it works!

**Pull request merged**
