### PR TITLE
docs: improve docs content

### PR DESCRIPTION
**Pull request by tromika**
## What kind of change does this pull request introduce?

Improving the docs, fixing typos, and making sure the documentation is clear.

## What is the new behavior?
The docs are crystal clear.

## Checklist

- [ ] Documentation
- [ ] Ready to be merged

### CODE REVIEW

**Review by danilowoz — APPROVED** [review]

**Comment by tromika** [comment]
@sannek added some improvements from my side. For the rest, for me, it's logically clear. On the other hand, I can't assess in many cases it's clear enough to use it.

**Comment by sannek** [comment]
Looks good to me! I suppose I should also use this branch to do my copy editing/nitpicking, because otherwise i'm looking at dated stuff?

I'll fix the merge conflict and go over it as well.

**Comment by tromika** [comment]
Yes please! Also I'm still planning to go through on this once again. So it's a good collaborative experience in CSB projects! Thanks!

**Comment by sannek** [comment]
Actually - i realised that my interactive examples aren't on this branch - so we really should _merge_ this one asap and get on a new branch.

I'm still finishing up on the `custom-content` guide, but I'm a bit stuck on it so figured I'd take a little break to edit the rest first.

**Review by sannek — APPROVED** [review]

**Pull request merged**
